// Copy compiled ABIs from Foundry's out/ into @proofbet/shared (the codegen seam).
// Emits TypeScript `as const` modules so wagmi/viem infer fully-typed calls.
// Run after `forge build`. ABIs are NEVER hand-copied. Usage: node scripts/sync-abi.mjs
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "out");
const abiDir = join(here, "..", "..", "packages", "shared", "src", "abi");
mkdirSync(abiDir, { recursive: true });

// [Solidity name, artifact dir, exported const identifier]
const ARTIFACTS = [
  ["IProofBet", "IProofBet.sol", "iProofBetAbi"],
  ["ProofBet", "ProofBet.sol", "proofBetAbi"],
  ["Proofs", "Proofs.sol", "proofsAbi"],
];

let synced = 0;
for (const [name, dir, ident] of ARTIFACTS) {
  const src = join(outDir, dir, `${name}.json`);
  if (!existsSync(src)) {
    console.warn(`· skip ${name} (not built yet)`);
    continue;
  }
  const { abi } = JSON.parse(readFileSync(src, "utf8"));
  const body =
    `// AUTO-GENERATED by contracts/scripts/sync-abi.mjs — do not edit by hand.\n` +
    `export const ${ident} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(abiDir, `${name}.ts`), body);
  console.log(`✓ synced ${name} → packages/shared/src/abi/${name}.ts`);
  synced++;
}

if (synced === 0) {
  console.error("No ABIs synced — run `forge build` first.");
  process.exit(1);
}
